# Generated by Django 5.2.14 on 2026-06-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customrole_user_custom_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
