# Generated by Django 5.2.14 on 2026-06-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='raw_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('hod', 'HOD'), ('hr', 'HR'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('hostel_warden', 'Hostel Warden'), ('placement_officer', 'Placement Officer'), ('transport_incharge', 'Transport Incharge'), ('alumni_coordinator', 'Alumni Coordinator'), ('parent', 'Parent'), ('custom', 'Custom')], default='admin', max_length=30),
        ),
    ]
